selected_game: mhs3
capture:
  device_index: 1
  width: 1920
  height: 1080
  fps: 30
virtual_camera:
  enabled: true
ocr:
  engine: easyocr
  poll_fps: 3.0
  languages:
  - en
  gpu: true
  debounce_frames: 3
  continuous: true
  monster_persist_s: 7.0
  monster_persist_end_s: 1.0
ui:
  always_on_top: false
games:
  mhs3:
    regions:
      monster_names:
      - x: 217
        y: 21
        w: 1665
        h: 136
      battle_end:
        x: 14
        y: 14
        w: 457
        h: 189
    keywords:
      battle_end:
      - result
